backend:
  name: git-gateway
  branch: feature/personalized-tours

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      
  - folder: "src/pages/tour"
    label: "Tour"
    name: "tour"
    create: true
    fields:
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "tour-page"

      - label: Tour Title
        name: title
        widget: string

      - label: Hero Section
        name: hero
        widget: object
        fields: 
        - label: Background Image
          name: image
          widget: image
        - label: Tour Subtitle
          name: subtitle
          widget: string
        - label: Tour Cta Text
          name: ctaText
          widget: string
        - label: Tour Cta Link
          name: ctaLink
          widget: string

      - label: Description Section
        name: tourDescription
        widget: object
        fields: 
        - label: title
          name: title
          widget: string
        - label: body
          name: body
          widget: text 
        - label: Side Image
          name: image
          widget: image

      - label: Gallery
        name: gallery
        widget: object
        fields: 
          - label: Mid Text Title
            name: textTitle
            widget: string
          - label: Text body
            name: textBody
            widget: text
      - label: Upper Gallery
        name: galleryUpper
        widget: list
        fields: 
          - label: Image
            name: image
            widget: image
      - label: Bottom Gallery
        name: galleryBottom
        widget: list
        fields: 
          - label: Image
            name: image
            widget: image
      - label: Blog Section Title
        name: blogSectionTitle

      - label: CalendarTitle
        name: calendarTitle
        widget: string

      - label: Calendar Body
        name: calendarBody
        widget: text

      - label: Calendar Notes
        name: calendarNotes
        widget: text

      - label: Aviability dates
        name: aviabilityDates
        widget: list
        fields: 
          - label: Start Date
            name: startDate
            widget: date
            default: ""
            format: "MMM Do YY"
            
          - label: End Date
            name: endDate
            widget: date
            default: ""
            format: "MMM Do YY"

      - label: Instagram username
        name: instagramUsername
        widget: string

      - label: Instagram Photos
        name: instagramPhotos
        widget: list
        fields: 
          - label: Photo id
            name: id
            widget: string


  - name: "pages"
    label: "Pages"
    files:
      - file: src/pages/index.md
        label: Homepage
        name: home
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: home-page

          - label: Hero Section
            name: hero
            widget: object
            fields:
              - label: Hero Title
                name: title
                widget: string

              - label: Payoff
                name: payoff
                widget: text

              - label: Call to action Text  
                name: ctaText
                widget: string

              - label: Call to action Action (url)
                name: ctaUrl
                widget: string

              - label: Hero Background Image
                name: image
                widget: image

          - label: Tour Section Title
            name: tourSectionTitle
            widget: string

          - label: Blog News title
            name: blogNewsTitle
            widget: string

          - label: Contact section title
            name: contactSectionTitle
            widget: string

          - label: Info Section
            name: infoSection
            widget: object
            fields: 
              - label: title
                name: title
                widget: string

              # - label: Content
              #   name: body
              #   widget: markdown
              
              - label: Call to action text
                name: ctaText
                widget: string

              - label: Call to action Action
                name: ctaUrl
                widget: string
          ## Markdown filed must be inside root element
          - label: Content
            name: body
            widget: markdown

      - file: "src/pages/i-am-angelina/index.md"
        label: "I am Angelina Page"
        name: "i-am-angelina"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "i-am-angelina-page"}

      - file: "src/pages/personalized-events/index.md"
        label: "Personalized Events Page"
        name: "personalized-events"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "personalized-events-page"
          - label: Title
            name: title
            widget: string
          - label: Hero
            name: hero
            widget: object
            fields:
            - label: subtitle
              name: subtitle
              widget: text
            - label: Background Image
              name: bgImage
              widget: image
            - label: Call to action Text
              name: ctaText
              widget: string
            - label: Call to action Link
              name: ctaLink
              widget: string
          - label: Description title
            name: descriptionTitle
            widget: string
          - label: Description Body
            name: body
            widget: markdown
          - label: Gallery
            name: personalizedEventsGallery
            widget: list
            fields: 
              - label: Image
                name: image
                widget: image
          - label: Mid Description title
            name: midDescriptionTitle
            widget: string
          - label: Mid Description body
            name: midDescriptionBody
            widget: text
          - label: Description Cards
            name: descriptionCards
            widget: list
            fields: 
              - label: title
                name: title
                widget: string
              - label: Body
                name: body
                widget: text
          - label: Blog Section Title
            name: blogSectionTitle
            widget: string
          - label: Contact Section Title
            name: contactSectionTitle
            widget: string
            
