backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/i-am-angelina/index.md"
        label: "I am Angelina Page"
        name: "i-am-angelina"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "i-am-angelina-page"}

      - file: "src/pages/tour/index.md"
        label: "tour Page"
        name: "tour"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "tour-page"}
      - file: "src/pages/personalized-events/index.md"
        label: "Personalized Events Page"
        name: "personalized-events"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "personalized-events-page"}