backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "options"
    label: "Site Options"
    files:
      - file: src/options/headerAndFooter.md
        label: Header and Footer options
        name: configuration
        preview: false
        fields: 
          - label: Data type
            name: dataType
            widget: hidden
            default: headerAndFooterOptions
          - label: Menu Items
            name: menuItems
            widget: list
            fields:
              - label: Title
                name: title
                widget: string
              - label: Path
                name: path
                widget: string
              - label: Region Dropdown
                name: regionDropdown
                widget: 
                default: false
          - label: Menu CTA text
            name: menuCtaText
            widget: string
          - label: Menu CTA link
            name: menuCtaLink
            widget: string
          - label: Footer Menu
            name: footerMenu
            widget: list
            fields:
              - label: title
                name: title
                widget: string
              - label: url
                name: url
                widget: string
          - label: FooterContacts
            name: footerContacts
            widget: object
            fields:
              - label: Telephone Number
                name: phoneNumber
                widget: string
              - label: Email address
                name: emailAddress
                widget: string
          - label: Credits text
            name: creditsText
            widget: text
          - label: Copyright text
            name: copyrightText
            widget: text
          - label: Social Informations
            name: socialInfo
            widget: object
            fields:
              - label: Facebook Url
                name: facebookUrl
                widget: string
              - label: Instagram username
                name: instagramUsername
                widget: string


  - folder: src/pages/tour
    label: Tour
    name: tour
    create: true
    fields:
      - label: Template Key
        name: templateKey
        widget: hidden
        default: tour-page

      - label: Tour Title
        name: title
        widget: string
        default: Lorem ipsum dolor set in Sardinia
      
      - label: Tour Highlights
        name: highlights
        widget: text
        default: Here you can insert your main featues of the tour, they will be shown in homepage tour card
        
      - label: Tour Region
        name: region
        widget: select
        options: [Abruzzo,Apulia,Basilicata,Calabria,Campania,Emilia-Romagna,Friuli-Venezia-Giulia,Latium,Liguria,Lombardy,Marche,Molise,Piedmont,Sardinia,Sicily,Tuscany,Trentino,Umbria,Aosta_Valley,Veneto]

      - label: Hero Section
        name: hero
        widget: object
        default: { image: https://source.unsplash.com/collection/148531/1920x1080, subtitle: "Your tour subtitle, lorem ipsum dolor set", ctaText: Your call to action }
        fields: 
        - label: Background Image
          name: image
          widget: image

        - label: Hero Background Dark Overlay
          name: heroBgOverlay
          widget: boolean
          default: false

        - label: Tour Subtitle
          name: subtitle
          widget: string

        - label: Tour Cta Text
          name: ctaText
          widget: string

        - label: Tour Cta Link
          name: ctaLink
          widget: string

      - label: Description Section
        name: tourDescription
        widget: object
        default: { title: Section title, body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima deserunt dicta distinctio nisi expedita iste quo delectus tempore voluptates explicabo fugiat, accusantium doloribus voluptatem reiciendis! Doloremque non quod vitae facilis", image: https://source.unsplash.com/collection/148531/1920x1080 }
        fields: 
        - label: title
          name: title
          widget: string

        - label: body
          name: body
          widget: text 
          
        - label: Side Image
          name: image
          widget: image

      - label: Tour Short Description
        name: tourShortDescription
        widget: text
        default: This description will be shown in homepage card

      - label: Gallery
        name: gallery
        widget: object
        default: { textTitle: Gallery section title, textBody: This text goes in Gallery section and describes the tour. }
        fields: 
          - label: Mid Text Title
            name: textTitle
            widget: string

          - label: Text body
            name: textBody
            widget: text

      - label: Upper Gallery
        name: galleryUpper
        widget: list
        default: [{ image: https://source.unsplash.com/collection/148531/800x800 }, { image: https://source.unsplash.com/collection/148531/800x800 }, { image: https://source.unsplash.com/collection/148531/800x800 }, { image: https://source.unsplash.com/collection/148531/800x800 }, { image: https://source.unsplash.com/collection/148531/800x800 }, { image: https://source.unsplash.com/collection/148531/800x800 }, ]
        fields: 
          - label: Image
            name: image
            widget: image
      # - label: Bottom Gallery
      #   name: galleryBottom
      #   widget: list
      #   default: [{ image: https://source.unsplash.com/collection/148531/800x800 }, { image: https://source.unsplash.com/collection/148531/800x800 }, { image: https://source.unsplash.com/collection/148531/800x800 }, { image: https://source.unsplash.com/collection/148531/800x800 }, { image: https://source.unsplash.com/collection/148531/800x800 }, { image: https://source.unsplash.com/collection/148531/800x800 }, ]
      #   fields: 
      #     - label: Image
      #       name: image
      #       widget: image
      - label: Description Cards
        name: descriptionCards
        widget: list
        default: [{ body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sunt asperiores, vero molestias facilis fuga est recusandae totam. Neque, quae voluptatibus reprehenderit tempora quia temporibus. Eum tenetur dolor temporibus voluptate veniam.", subtitle: Lorem ipsum dolor set, title: Lorem Ipsum }, { body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sunt asperiores, vero molestias facilis fuga est recusandae totam. Neque, quae voluptatibus reprehenderit tempora quia temporibus. Eum tenetur dolor temporibus voluptate veniam.", subtitle: Lorem ipsum dolor set, title: Lorem Ipsum }, { body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sunt asperiores, vero molestias facilis fuga est recusandae totam. Neque, quae voluptatibus reprehenderit tempora quia temporibus. Eum tenetur dolor temporibus voluptate veniam.", subtitle: Lorem ipsum dolor set, title: Lorem Ipsum }, { body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sunt asperiores, vero molestias facilis fuga est recusandae totam. Neque, quae voluptatibus reprehenderit tempora quia temporibus. Eum tenetur dolor temporibus voluptate veniam.", subtitle: Lorem ipsum dolor set, title: Lorem Ipsum }, { body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sunt asperiores, vero molestias facilis fuga est recusandae totam. Neque, quae voluptatibus reprehenderit tempora quia temporibus. Eum tenetur dolor temporibus voluptate veniam.", subtitle: Lorem ipsum dolor set, title: Lorem Ipsum }, { body: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Sunt asperiores, vero molestias facilis fuga est recusandae totam. Neque, quae voluptatibus reprehenderit tempora quia temporibus. Eum tenetur dolor temporibus voluptate veniam.", subtitle: Lorem ipsum dolor set, title: Lorem Ipsum }, ]
        fields: 
          - label: title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
          - label: Body
            name: body
            widget: text

      - label: Blog Section Title
        name: blogSectionTitle
        widget: string
        default: Your blog section title

      - label: CalendarTitle
        name: calendarTitle
        widget: string
        default: Your calendar section title

      - label: Calendar Body
        name: calendarBody
        widget: text
        default: Your calendar section body, Lorem ipsum dolor sit amet consectetur adipisicing elit. Minima deserunt dicta distinctio nisi expedita iste quo delectus tempore

      - label: Calendar Notes
        name: calendarNotes
        widget: string
        default: You may insert some notes under the calendar

      - label: Aviability dates
        name: aviabilityDates
        widget: list
        fields: 
          - label: Start Date
            name: startDate
            widget: date
            default: ""
            
          - label: End Date
            name: endDate
            widget: date
            default: ""

      - label: Instagram username
        name: instagramUsername
        widget: string
        default: '@italian_flavours'

      - label: Instagram Photos
        name: instagramPhotos
        widget: list
        default: [{ id: BnBIn3mhjRK }, { id: Bmxc7yEhvOE }, { id: BmeZ3hjhm7m }, { id: BmrImF3htke }, ]
        fields: 
          - label: Photo id
            name: id
            widget: string


  - name: "pages"
    label: "Pages"
    files:
      - file: src/pages/index.md
        label: Homepage
        name: home
        fields:
          - label: Template Key
            name: templateKey
            widget: hidden
            default: home-page

          - label: Hero Section
            name: hero
            widget: object
            fields:
              - label: Hero Title
                name: title
                widget: string

              - label: Payoff
                name: payoff
                widget: text

              - label: Call to action Text  
                name: ctaText
                widget: string

              - label: Call to action Action (url)
                name: ctaUrl
                widget: string

              - label: Hero Background Image
                name: image
                widget: image
              
              - label: Hero Background Dark Overlay
                name: heroBgOverlay
                widget: boolean
                default: false

          - label: Tour Section Title
            name: tourSectionTitle
            widget: string

          - label: Blog News title
            name: blogNewsTitle
            widget: string

          - label: Contact section title
            name: contactSectionTitle
            widget: string

          - label: Contact form options
            name: contactFormOptions
            widget: list
            fields: 
              - label: title
                name: title
                widget: string

          - label: Info Section
            name: infoSection
            widget: object
            fields: 
              - label: title
                name: title
                widget: string

              # - label: Content
              #   name: body
              #   widget: markdown
              
              - label: Call to action text
                name: ctaText
                widget: string

              - label: Call to action Action
                name: ctaUrl
                widget: string
          ## Markdown filed must be inside root element
          - label: Info Section Content
            name: body
            widget: markdown

      - file: "src/pages/i-am-angelina/index.md"
        label: "I am Angelina Page"
        name: "i-am-angelina"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "i-am-angelina-page"
          - label: title
            name: title
            widget: string
          - label: Hero
            name: hero
            widget: object
            fields:
            - label: subtitle
              name: subtitle
              widget: text
            - label: Background Image
              name: bgImage
              widget: image
            - label: Hero Background Dark Overlay
              name: heroBgOverlay
              widget: boolean
              default: false
            - label: Call to action Text
              name: ctaText
              widget: string
            - label: Call to action Link
              name: ctaLink
              widget: string
          - label: Description title
            name: descriptionTitle
            widget: string
          - label: Description Body
            name: body
            widget: markdown
          - label: Contact Section Title
            name: contactSectionTitle
            widget: string
          - label: Instagram Photos
            name: instagramPhotos
            widget: list
            fields: 
              - label: Photo id
                name: id
                widget: string

      - file: "src/pages/personalized-events/index.md"
        label: "Personalized Events Page"
        name: "personalized-events"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "personalized-events-page"
          - label: Title
            name: title
            widget: string
          - label: Hero
            name: hero
            widget: object
            fields:
            - label: subtitle
              name: subtitle
              widget: text
            - label: Background Image
              name: bgImage
              widget: image
            - label: Hero Background Dark Overlay
              name: heroBgOverlay
              widget: boolean
              default: false
            - label: Call to action Text
              name: ctaText
              widget: string
            - label: Call to action Link
              name: ctaLink
              widget: string
          - label: Description title
            name: descriptionTitle
            widget: string
          - label: Description Body
            name: body
            widget: markdown
          - label: Gallery
            name: personalizedEventsGallery
            widget: list
            fields: 
              - label: Image
                name: image
                widget: image
          - label: Mid Description title
            name: midDescriptionTitle
            widget: string
          - label: Mid Description body
            name: midDescriptionBody
            widget: text
          - label: Description Cards
            name: descriptionCards
            widget: list
            fields: 
              - label: title
                name: title
                widget: string
              - label: Body
                name: body
                widget: text
          - label: Blog Section Title
            name: blogSectionTitle
            widget: string
          - label: Contact Section Title
            name: contactSectionTitle
            widget: string
          - label: Instagram Photos
            name: instagramPhotos
            widget: list
            fields: 
              - label: Photo id
                name: id
                widget: string
            
